### ISSUE TITLE
Widgets binding error after upgrading flutter version to 2.13.0-0.1.pre

### ISSUE THREAD

**Issue by muhammadmateen027** [brianegan/flutter_redux#231] opened 2022-04-20 09:36 UTC
I'm facing below warnings since I upgraded the flutter version to `2.13.0-0.1.pre`.

**Warning**: 
```dart
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux-0.9.0/lib/flutter_redux.dart:474:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding'
which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((_) {
                     ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_redux-0.9.0/lib/flutter_redux.dart:577:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding'
which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((_) {
```

**Flutter version**:
```dart
Flutter 2.13.0-0.1.pre • channel unknown • unknown source
Framework • revision 13a2fb10b8 (8 days ago) • 2022-04-12 15:34:25 -0500
Engine • revision 499984f99c
Tools • Dart 2.17.0 (build 2.17.0-266.1.beta) • DevTools 2.12.1
```

**Comment by brianegan** [comment] 2022-04-20 09:55
Thanks! Duplicate of https://github.com/brianegan/flutter_redux/issues/228. You can already find a pre-release that fixes the issue on Pub as well :)

**Closed as completed by brianegan** 2022-04-20 09:55 UTC
